//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
namespace IdentifyProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SightedDB
    {
        public int SID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Name { get; set; }
        public string Age { get; set; }
        public string Date { get; set; }
        public string CitizenName { get; set; }
        public string CitizenContact { get; set; }
        public string Description { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public string FIRNO { get; set; }
        public string Status { get; set; }
        [DisplayName("Image")]
        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public SightedDB()
        {
            ImagePath = "~/AppFiles/Images/default.png";
        }


    }
}
